version: "3.5"
services:
  backend_user:
    build: .
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    ports:
      - 5002:5000
    networks:
      - gateway
      - back_users

networks:
  back_users:
    name: back_users
  gateway:
    name: gateway