version: "3.5"
services:
  db:
    image: mariadb:10.5.8
    environment: 
      MYSQL_ROOT_PASSWORD: eccoar_db_pass
      MYSQL_DATABASE: eccoar_user_db
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql

  backend_user:
    build: .
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    ports:
      - 5002:5000
    environment:
      APP_PORT: 5000
      TYPEORM_CONNECTION: mysql
      TYPEORM_HOST: db
      TYPEORM_USERNAME: root
      TYPEORM_PASSWORD: eccoar_db_pass
      TYPEORM_DATABASE: eccoar_user_db
      TYPEORM_SYNCHRONIZE: "true"
      TYPEORM_PORT: 3306
      TYPEORM_LOGGING: "true"
      TYPEORM_ENTITIES: src/entity/**/*.ts
      TYPEORM_MIGRATIONS: src/migration/**/*.ts
      TYPEORM_SUBSCRIBERS: src/subscriber/**/*.ts
      TYPEORM_ENTITIES_DIR: src/entity
      TYPEORM_MIGRATIONS_DIR: src/migration
      TYPEORM_SUBSCRIBERS_DIR: src/subscriber

volumes:
  mariadb_data:
    driver: local